version: "3"

networks:
  demo-network:
    driver: bridge 

services:
  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-local.yaml
    volumes:
      - ./loki/loki-local.yaml:/etc/loki/loki-local.yaml
    networks:
      - demo-network

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - ./promtail/promtail-local.yaml:/etc/promtail/promtail-local.yaml
      - ./logs:/var/spring-boot-log
      - ../../logs:/var/other-log
      - ../../json:/var/json-log
    command: -config.file=/etc/promtail/promtail-local.yaml
    networks:
      - demo-network
      
  spring-boot:
    container_name: spring-boot
    build:
      context: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      username: ${username}
      password: ${password}
      dbhost: ${dbhost}
      database: ${database}
    networks:
      - demo-network
      
  mysqldb:
    image: mysql:8.0.22
    container_name: mysqldb
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: myjdbc
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - demo-network
      
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    depends_on:
      - spring-boot 
    networks:
      - demo-network    

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - demo-network