global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'spring boot app input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['spring-boot:8080']
        labels:
          application: spring-boot-app